version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.2
  jobs:
    build: null
    deploy: null
workflows:
  build_and_test:
    jobs:
      - build
      - katalon-studio/run:
          version: latest
          command_arguments: >-
            -browserType='Chrome' -retry=0 -statusDelay=15 -testSuitePath='Test
            Suites/Sanity Test/Sanity Test Execution'

            - deploy:
                requires:
                  - katalon-studio/run
