version: 2.1
orbs:
    katalon-studio: katalon/katalon-studio@23.0.11
    
workflows:
  build:
    jobs:
        - katalon-studio/run:
                version: "latest"
          command_arguments: 'katalonc.sh -statusDelay=30 -retry=0 -projectPath="/root/project/TcircleCI-orb-Demo.prj" -testSuitePath="Test Suites/Sanity Test/Sanity Test Execution" -executionProfile=“default” -browserType="Chrome (headless)" -apiKey=9ae2eb91-3c45-41bc-8eb9-a8a35f6c2dca'
          
      - deploy:
          requires:
            - katalon-studio/run
