version: 2.1
orbs:
    katalon-studio: katalon/katalon-studio@23.0.11
    
workflows:
  build:
    jobs:
        - katalon-studio/run:
                version: "latest"
          command_arguments: '-browserType="Chrome" -retry=3 -statusDelay=16 -testSuitePath="Test Suites/Sanity Test/Sanity Test Execution"'
