version: 2.1
orbs:
  katalon-studio: katalon/katalon-studio@23.0.8
  
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy to Staging Environment
          command: |
            git push --force https://heroku:c3631a7f-fa25-43d5-9489-69e66286c978@git.heroku.com/webinar-demo-kat-staging.git master
  
  deploy:
    docker:
      - image: buildpack-deps:trusty
      
    steps:
      - checkout
      - run:
          name: Deploy to Production Environment
          command: |
            git push --force https://heroku:c3631a7f-fa25-43d5-9489-69e66286c978@git.heroku.com/webinar-demo-kat-production.git master
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - katalon-studio/run:
          requires:
            - build
          version: "latest"
          command_arguments: 'katalonc.sh -statusDelay=30 -retry=0 -projectPath="/root/project/TcircleCI-orb-Demo.prj" -testSuitePath="Test Suites/Sanity Test/Sanity Test Execution" -executionProfile=“default” -browserType="Chrome (headless)" -apiKey=9ae2eb91-3c45-41bc-8eb9-a8a35f6c2dca'
          
      - deploy:
          requires:
            - katalon-studio/run
